services:
  - type: web
    name: clinic-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PHP_VERSION
        value: 8.2
      - key: DATABASE_URL
        sync: false
